export enum TravelTypesSet {
  RELAXATION = "RELAXATION",
  ADVENTURE = "ADVENTURE",
  CULTURAL = "CULTURAL",
  HIKING = "HIKING",
  BEACH = "BEACH",
  GASTRONOMIC = "GASTRONOMIC",
  ROAD_TRIP = "ROAD_TRIP",
  CRUISE = "CRUISE",
  FAMILY_TRIP = "FAMILY_TRIP",
  FRIENDS_TRIP = "FRIENDS_TRIP",
  ECO_FRIENDLY = "ECO_FRIENDLY",
}
